name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MIX_ENV: test

jobs:
  mix_test:
    name: mix test (OTP ${{ matrix.otp }} | Elixir ${{ matrix.elixir }})
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          # Test on latest stable
          - elixir: '1.18.4'
            otp: '27.3'
          
          # Test on minimum supported versions
          - elixir: '1.18.4'
            otp: '26.2'
          
          # Lint and check on latest
          - elixir: '1.19.1'
            otp: '28.1'
            lint: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Restore deps and _build cache
      uses: actions/cache@v4
      with:
        path: |
          deps
          _build
        key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

    - name: Install dependencies
      run: mix deps.get

    - name: Remove compiled application files
      run: mix clean

    - name: Compile dependencies
      if: ${{ !matrix.lint }}
      run: mix compile

    - name: Compile with warnings as errors
      if: ${{ matrix.lint }}
      run: mix compile --warnings-as-errors

    - name: Check formatting
      if: ${{ matrix.lint }}
      run: mix format --check-formatted

    - name: Run Credo
      if: ${{ matrix.lint }}
      run: mix credo --strict

    - name: Run Dialyzer
      if: ${{ matrix.lint }}
      run: mix dialyzer --halt-exit-status

    - name: Run tests
      run: mix test --warnings-as-errors
